variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_name" {}
variable "public_subnet_cidr_az1" {}
variable "public_subnet_cidr_az2" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}